version: 2.1

jobs:
  deploy_master:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Clone submodule
          command: |
            git submodule init
            git submodule update
      - run:
          name: yarn install
          command: yarn upgrade
      - run:
          name: Compile scss
          command: yarn build
      - run:
          name: Deploy to Firebase
          command: npx firebase-tools deploy -m "$(git log -1 --pretty=format:'%h':' %s')" --token="${FIREBASE_TOKEN}"

workflows:
  version: 2.1
  deploy_to_firebase:
    jobs:
      - deploy_master:
        filters:
          branches:
            only: master