version: 2.1
jobs:
  deploy_master:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
        name: Clone submodule
        command: git submodule init && git submodule update
      - run:
        name: yarn install
        command: yarn install --flozen-lockfile
      - run:
        name: Compile scss
        command: node_modules/.bin/gulp
      - run:
        name: Deploy to Firebase
        command: npx firebase-tools deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  deploy_master:
    jobs:
      - deploy_master:
        filters:
          branches:
            only: master